name: Test License
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner-windows-2
        unity-version:
          - 2021.3.20f1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: ${{ matrix.unity-version }}
      - name: Activate unity
        uses: ./
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_AUTHENTICATOR_KEY }}
